 # Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  release:
    types: [published]
    
# List of jobs
jobs:
  copy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pushes css file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'tokens/css/variables.css'
        destination_repo: 'aliasgs/react-demo'
        destination_folder: 'src/tokens/'
        user_email: 'syd.1991@gmail.com'
        user_name: 'aliasgs'
        commit_message: 'design tokens css updated!'
