name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer data/tokens.json tokens/output.json
      # Convert tokens according to Style Dictionary config
      - run: npx style-dictionary build --config config.json
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
  
  notify:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes css file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'tokens/css/variables.css'
        destination_repo: 'aliasgs/react-demo'
        destination_folder: 'src/tokens'
        user_email: 'syd.1991@gmail.com'
        user_name: 'aliasgs'
        commit_message: 'design tokens css updated!'
    
    - name: Pushes scss file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'tokens/scss/_variables.scss'
        destination_repo: 'aliasgs/react-demo'
        destination_folder: 'src/tokens'
        user_email: 'syd.1991@gmail.com'
        user_name: 'aliasgs'
        commit_message: 'design tokens scss updated!'

