name: CI
on: [push]

jobs:

  delete:
    runs-on: ubuntu-latest     
    # Job steps
    steps:
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
         path: tokens/css/variables.css
