name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'tokens/css/variables.css'
        destination_repo: 'aliasgs/react-demo'
        destination_folder: 'src'
        user_email: 'syd.1991@gmail.com'
        user_name: 'aliasgs'
        commit_message: 'A custom message for the commit'
